version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=terraform_backend
    ports:
      - '5432:5432'
    volumes: 
      - /mnt/data/tfdb:/var/lib/postgresql/data
  dns:
    restart: always
    image: strm/dnsmasq
    # volumes:
      # - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN