version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=terraform_backend
    ports:
      - '5433:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
  dns:
    restart: always
    image: strm/dnsmasq
    volumes:
     - ./config/dnsmasq.conf:/etc/dnsmasq.conf
     - ./config/hosts:/etc/hosts
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN